### ISSUE TITLE
dev workflow question

### ISSUE THREAD

**Issue by brianium** [roman01la/cljss#15]
Was attempting to get started on #7 and I hit a minor snag with getting up and running.

Maybe I'm not a wizard at Clojure yet (entirely possible) - but I feel like I had to jump through some hoops to get a repl connected for development. Wondering if you could shed some light on what your development workflow looks like @roman01la 

I've been used to figwheel in the past, but I wasn't in a rush to introduce a bunch of new things to the project :)

To get a dev repl up and running I had to do the following within the `examples/` dir:

```
$ lein trampoline cljsbuild repl-listen
```

Which required a web server to serve the example files - so I just grabbed python because it was handy:

```
$ python -m SimpleHTTPServer

Serving HTTP on 0.0.0.0 port 8000 ...
```

Then hitting `localhost:8000` I am connected to a repl. Is the idea to keep a watch on source files using something like `lein cljsbuild auto dev` to reload changes?

Any insight on making this smoother would be greatly appreciated. Any documentation or links would be great (especially if you have something on integrating with emacs/cider - but I can figure this out if not)

Thanks a lot! Really hoping I can contribute to this library

**Comment by brianium** [comment]
I should add the above approach also required that I add

```clojure
(clojure.browser.repl/connect "http://localhost:9000/repl")
```

To `example.core`

**Comment by roman01la** [comment]
@brianium I'm not using REPL or Figwheel in this particular project. But if you want, you can use whatever makes your dev workflow easier :)

**Comment by brianium** [comment]
Awesome! Thought maybe I was missing something. Thanks!
