### ISSUE TITLE
Invalid props passed along (reagent)

### ISSUE THREAD

**Issue by brianium** [roman01la/cljss#17]
I've only tested this with reagent - but I imagine it's an issue anywhere props are just passed through directly to react.

All props for a styled component are passed to the underlying component. This results in a warning if react doesn't recognize the prop.

Since props are a pretty big piece of configuring styled components, maybe there is something we can do to filter out invalid props before the call to `createElement`? Maybe wrap native html elements?

![screen shot 2017-09-08 at 7 30 41 am](https://user-images.githubusercontent.com/636651/30209886-2850d260-9468-11e7-8fb2-f4b76d11a570.png)

**Comment by brianium** [comment]
https://github.com/styled-components/styled-components/issues/439 seems related

**Comment by brianium** [comment]
And https://github.com/styled-components/styled-components/issues/135

**Comment by roman01la** [comment]
AFAIK this is the issue in all CSS-in-JS libraries. cljss solves this partially by using keywords in styles declaration to read from props, those props would be removed then

**Comment by roman01la** [comment]
We could try to use meta as a hint to determine which attribute should be removed

```clojure
(defstyled Button :button
  {:padding ^:size #(case ...)})

(Button {:size :large})
```

**Comment by roman01la** [comment]
We can use either a type hint like meta `^size`, which will become `:tag` field on meta object or set it to a special field for example `:prop` using `^{:prop :size}` notation

**Comment by brianium** [comment]
Both are really intriguing to me. I think style makes sense as meta. The little bit of extra syntax is not a problem for me - but wonder if it would deter others? Personally, I find the `:tag` variant is more appealing

```clojure
(defstyled label :label
  {:margin ^:position #(if (= "top" %) ...})
```

That would solve my problem nicely :) - and I think it is still clear what "prop" is being used for the style when you use it:

```clojure
[label {:position "top"} "some label"]
```

Seems like an easy win to me ¯\\\_(ツ)_/¯

**Comment by roman01la** [comment]
I also like the shorter. But keep in mind that we are talking about `^prop` and not `^:prop`. The first will be a symbol `prop` in a field `:tag`, but the latter will be a separate field `:prop` in meta object with value of `true`. This means that even though the latter syntax is more attractive, there's no straightforward way to find that prop in meta object then.

**Comment by roman01la** [comment]
@brianium if you are going to implement this here's how I'd do it: since styles declaration is static, it's possible to extract all `:tag` symbols into a set in `defstyled` macro, convert them into keywords and pass that collection into runtime function which will `dissoc` on props map.

**Comment by brianium** [comment]
@roman01la great! I'm looking at it right now - I'll be sure to ask if I get stuck on something. Thanks!

**Comment by brianium** [comment]
Spent a little time setting up a workflow in #18 - and then started tinkering with some things on this.

I don't think I have has much clarity as I thought I did on the use of `:tag`.

In your [comment above](https://github.com/roman01la/cljss/issues/17#issuecomment-328094022), you gave an example using `^:size`. How would `^size` work if the symbol `size` has not yet been defined?

Also how would we articulate a dependency on multiple props? Without a tag - it could be `^:size ^:position`, but that doesn't work for `:tag`.

Would you mind showing an example of client code that would use the `:tag` approach?

**Comment by roman01la** [comment]
You are right, tag requires a symbol to be defined. I didn't think of it first. As for having multiple props mapping to a single style prop I'm not sure if this is a valid use case 🤔

**Comment by brianium** [comment]
Back to the drawing board I suppose 🤔

**Comment by brianium** [comment]
Is it worth maintaining a whitelist for a given tag? It seems this approach is generally frowned upon - and not bulletproof by any stretch, but it is the approach styled components currently uses - and it may be good enough in the short term?

**Comment by brianium** [comment]
Or perhaps a higher order function that allows something like [this](https://github.com/styled-components/styled-components/issues/439#issuecomment-327251673)?

**Comment by roman01la** [comment]
I think we could still rely on `^:attr` meta if we make sure that no other keys in meta map have values eq to `true`

**Comment by roman01la** [comment]
Another approach that could work is to use `with-meta`

```clojure
(def x {:attr (with-meta identity :size)})

(-> x :attr meta) ;; :size
```

**Comment by roman01la** [comment]
@brianium did you have a chance to play with `with-meta`?

**Comment by brianium** [comment]
Not yet.

Been working through a feature in an app with `cljss` and planning on tackling this as part of wrapping that up :)

I'm still a little unclear with the example above. Is the idea to supply meta to the function being used to calculate style? Would you mind showing a more realistic example of how that might be used in a component? Something like this?:

```clojure
(defstyled h1 :h1
  {:background-color (with-meta #(if (= "red" %) "red" "blue) :color)})
```

And this would be our queue that :color should be excluded from props when rendering the component?

**Comment by roman01la** [comment]
I just pushed to master an implementation with `with-meta`

**Comment by brianium** [comment]
Nice work!

Looking at the example:

```clojure
(rss/defstyled Input :input
    {:border-radius "2px"
     :border "1px solid #ccc"
     :padding (with-meta #(str (:padding-v %) " " "8px") :padding-v)})
```

I wonder if we could use the meta to make the function call even more succinct by using the meta value to just provide that prop as the function argument?

So instead of `#(str (:padding-v %) " " "8px")` we could just do `#(str % " " "8px")` - since we will know the intention is to use `:padding-v` because of the meta.

Thoughts?

**Comment by roman01la** [comment]
I like the idea. The meta could probably be a vector in case when there are multiple props would be used.

**Comment by roman01la** [comment]
@brianium Done https://github.com/roman01la/cljss/commit/101725ad8ba4e8011c774518ae04a10d00a8fecd

Do you think this could finally resolve the issue?

**Comment by brianium** [comment]
Perfect! Looks like you took care to support a single keyword or a vector of keywords. This will be super useful. I'll close the issue out. Thanks again!
