### ISSUE TITLE
Tag new release with "refer-macros" change

### ISSUE THREAD

**Issue by brianium** [roman01la/cljss#19]
Having some trouble compiling a project using `1.5.1` it is complaining about an invalid `:refer`  to `cljss.core/make-styled`  within `cljss/reagent.cljs`. I think the changes I made in #18 would fix this issue. Maybe tag a `1.5.2`?

**Comment by roman01la** [comment]
Sure, will do tomorrow. I suspect it complains only when used with Figwheel?

**Comment by brianium** [comment]
I am using figwheel - but I was getting an error after cleaning and using just cljsbuild.

```
$ lein clean
$ lein cljsbuild once dev
``

Thanks!

**Comment by roman01la** [comment]
published `1.5.2`
