### ISSUE TITLE
tests?

### ISSUE THREAD

**Issue by brianium** [roman01la/cljss#22]
I don't want to introduce something that creates work that no one wants to do, but how do you feel about adding a test suite for some of these things? I would be open to doing this if it's welcome.

Writing some tests would be a good exercise for me, and might also be nice to have if others start contributing.

Thoughts?

**Comment by roman01la** [comment]
sure, I don't mind

**Comment by brianium** [comment]
Cool cool. I'll close this for now to cut down on noise. Thanks!
