### ISSUE TITLE
Make classname readable during development.

### ISSUE THREAD

**Issue by Atsman** [roman01la/cljss#23]
Hello,

I have set goog.DEBUG to true. In ether case my css classes look like css-{id}.

I expected to see readable css classes, because now it is really not comfortable work with such names during development.

Any ideas?

Aleh

**Comment by roman01la** [comment]
Debugging mode just makes it possible to edit styles in devtools while suffering performance. In future versions I might go with ns + var name instead of a hash.

**Comment by roman01la** [comment]
In fact this will be needed when implementing SSR support, bc hashing in Clojure/Java works differently.

**Comment by roman01la** [comment]
fixed in aaf1a55b

**Comment by Atsman** [comment]
Thank you for so quick fix
