### ISSUE TITLE
Figwheel + defstyled

### ISSUE THREAD

**Issue by eneroth** [roman01la/cljss#25]
Do you have to do something in particular to get Figwheel to hot reload `defstyled` declarations when using `cljss.reagent`? Currently I'm a bit stuck with cold reloads to get them to update.

**Comment by roman01la** [comment]
I'm not sure, it should work. Do you have a project to reproduce this?

**Comment by eneroth** [comment]
I've stripped out everything but the skeleton, but this should reproduce it: [defstyled.zip](https://github.com/roman01la/cljss/files/1352254/defstyled.zip)

**Comment by roman01la** [comment]
Cool, thanks! Gonna take a look later today.

**Comment by roman01la** [comment]
Well, this seems to be a bug. Styles are not generated properly, I'll see if I can do anything to solve the issue.

**Comment by roman01la** [comment]
@eneroth Am I right in that only _static_ part of styles declaration doesn't get reloaded?

**Comment by roman01la** [comment]
fixed and published as v1.5.5

**Comment by eneroth** [comment]
Brilliant, thank you @roman01la!
