### ISSUE TITLE
Add Boot support

### ISSUE THREAD

**Issue by thenonameguy** [roman01la/cljss#3]
There could be a [boot-garden](https://github.com/martinklepsch/boot-garden)-like task that does the compilation process. This requires API changes though so these parameters can be passed through other than the cljs compiler options. 

Doing this would also open up the possibility to have separate css files (maybe per-component?) for HTTP2-supported browsers.

I'll take a stab at this on the weekend.

**Comment by roman01la** [comment]
@thenonameguy Why would you want to have separate CSS file per component? Everything is already bundled into a single file.
Other than that I would be happy to accept a PR to make this work for Boor.

**Comment by thenonameguy** [comment]
@roman01la For reasons described here: https://blog.cloudflare.com/http-2-for-web-developers/#stopconcatenatingfiles

**Comment by roman01la** [comment]
@thenonameguy This sounds reasonable, but I don't really want to overload this library with configuration options. Unless you find a nice way of doing this.

**Comment by roman01la** [comment]
closing this for now
