### ISSUE TITLE
devcards

### ISSUE THREAD

**Issue by brianium** [roman01la/cljss#32]
I have enjoyed seeing the tests added for new features 😄 

I've been using [devcards](https://github.com/bhauman/devcards) in a couple of other projects, and I think they may be a good replacement/supplement to the current `example` project.

They are a joy to work with, and they also serve as a good visual repl/test suite.

**Comment by brianium** [comment]
@roman01la I'm hoping to add a few more tests to existing code, but was wondering if you have any objections to introducing devcards as a more formal visual suite of tests? It has great integration with most of the react libs in cljs.

**Comment by roman01la** [comment]
Yes, sure. Indeed Devcards is good for organizing UIs.
