### ISSUE TITLE
Integers should assume "px" value

### ISSUE THREAD

**Issue by brianium** [roman01la/cljss#33]
In React - when providing an integer as a style value - the unit is assumed to be `px`. I also do this in reagent.

I would expect the following:

```clojure
(defstyled username :span
  {:margin-left 20})
```

To produce a valid style - however it omits `px` in the generated CSS. 

The example below does work:

```clojure
(defstyled username :span
  {:margin-left "20px"})
```

**Comment by roman01la** [comment]
This is something I was thinking about. Actually master now does this (not released). What I didn't like is that now since all numbers are blindly translated into `px`s, you can't do `:flex: 1` and similar unit-less CSS rules

**Comment by roman01la** [comment]
There are to options to handle this properly

1. Replicate React's behaviour (probably whitelisting)
2. Extend cljss DSL to CSS units e.g. `:font-size [3 :em]` or something

**Comment by brianium** [comment]
🤔  hmmmm - React's behavior would feel more familiar, and the DSL route seems to just make typing a css unit more awkward - i.e it might be preferable to just type "3em" instead of `[3 :em]`.

The point on `flex` is a good one 😄 

My vote would be to replicate React's behavior, or leave it as is.

**Comment by roman01la** [comment]
ok, I'll take a look at React's internals in this regard

**Comment by Atsman** [comment]
Second option is ugly, are u going to replicate React behaviour?

**Comment by roman01la** [comment]
@brianium I've been looking into it at it seems like React discourages unitless CSS values. In particular since React v15 it issues warnings about unitless values. In later versions they want to get rid off automatic units. So I think we should stick with explicit units. What do you think?

**Comment by roman01la** [comment]
Crazy idea: use namespaced keywords to specify units
```clj
[:h1
  {:css {:font-size/px  14
         :margin-top/em 1.5}}
  "hello"]
```

**Comment by brianium** [comment]
@roman01la ah - I would be in favor of keeping in step with react, though the namespaced key idea is very elegant.  I would be in favor if it were optional :)

Thanks for looking into this :)

**Comment by roman01la** [comment]
Great. Closing the issue then.
I'm definitely looking into this syntax :)

**Comment by Atsman** [comment]
What the point of that syntax ? If u need it, create functions and use them, why you trying to create some weird keyword syntax, like about media queries, now about units 

look here https://github.com/noprompt/garden/blob/master/src/garden/units.cljc
