### ISSUE TITLE
pseudo classes breaking styles in production builds

### ISSUE THREAD

**Issue by brianium** [roman01la/cljss#34]
@roman01la looks like you are working in here right now - so maybe this won't be an issue for long 😄 

I have a style:

```clojure
(defstyled selection :div
  {:margin-right  "10px"
   :border        "1px solid #ccc"
   :border-radius "4px"
   :padding       "4px"
   :font-size     "12px"
   :cursor        "pointer"
   :&:hover       {:background-color "#efefef"}})
```

This style works great during development - i.e `goog.DEBUG` is true.

However doing a production build seems to totally invalidate that style (i.e none of the styles apply at all). If I change the style to omit the pseudo class, it works fine:

```clojure
(defstyled selection :div
  {:margin-right  "10px"
   :border        "1px solid #ccc"
   :border-radius "4px"
   :padding       "4px"
   :font-size     "12px"
   :cursor        "pointer"})
```

**Comment by roman01la** [comment]
Yes, already fixed on master :) Will publish and close tomorrow.

**Comment by brianium** [comment]
Awesome. Looks like some of the latest test runs on Circle have been failing too - would you be open to updating tests to fit your new `build` module and getting the circle build passing again? Or is there anything I can do to help?

**Comment by brianium** [comment]
and as always - thank you!

**Comment by roman01la** [comment]
I'm not sure I'm done this change yet, so maybe we could fix tests later.

**Comment by brianium** [comment]
Sounds good 😄

**Comment by jasich** [comment]
Sorry late to the party, what's the current state?  Implemented but tests are failing?

**Comment by roman01la** [comment]
fixed in v1.5.12

**Comment by rundis** [comment]
I seem to have this issue too with 1.6.0 (also tried 1.5.12 and 1.5.13). Works great in dev, but not so much with advanced compilation. Tried with `:&:hover` and `:&:after`/`:&:before` (unsure how to represent `:nth-child(1)` btw)

**Comment by roman01la** [comment]
Hi! I’ll try to find time for this next week. Thanks for reporting!

**Comment by lwhorton** [comment]
I would like to bump this. It seems like there's something fishy with `goog.DEBUG false`. Any `cljss.reagent/defstyled` I have that uses either a pseudo `:&:hover/:active/:focus/etc.` or refers to the `::css/media` doesn't seem to inject any styles during a prod build. It does, however, seem to inject the `--vars` properly as well as assign class="" on the dom node. For example:
```
<h1 class="css_typography__h1 vars-1526034793"> Hi </h1>

.vars-1526034793 {
    --var-css_typography__h1-0: rgb(75,75,75);
    --var-css_typography__h1-1: 4.5rem 0 2.5rem;
}

... but no equivalent 
.css_typography__h1 { }
```
