### ISSUE TITLE
Support for re-agent class aliases

### ISSUE THREAD

**Issue by jasich** [roman01la/cljss#35]
In Reagent you can use either `:className`, `:class-name` or `:class`.  It seems that cljss doesn't support `:class-name` or `:class`, but it would to support them at least for the reagent defstyled macro.

**Comment by roman01la** [comment]
@jasich Is this really important? I'd stick with a single way to define class attribute.

**Comment by jasich** [comment]
The reagent project that I'm working on started off not using cljss so at the time I decided to use kebab case since it seems to read like idiomatic Clojure.  I've been moving newer components over cljss and now the project has a mix of the two.  I considered changing the existing instances of kebab case over, but it seems less ideal.

Time is precious so feel free to close this issue as this is a relatively minor annoyance.  I just wanted to put the idea out there.

**Comment by roman01la** [comment]
If you meant this for `defstyled`, I've just fixed it in 0932afed5
