### ISSUE TITLE
display name

### ISSUE THREAD

**Issue by kurtharriger** [roman01la/cljss#38]
When you install the react developer tools for chrome and view the react panel all the styled components are rendered with element name G_18695 in my case.  I assume the macro just needs to set a display name

<img width="725" alt="screen shot 2018-01-07 at 4 03 33 pm" src="https://user-images.githubusercontent.com/112603/34646741-7d3d13b8-f3c4-11e7-9f7f-0c53c226e2c7.png">

**Comment by roman01la** [comment]
Are they `defstyled` components?

**Comment by roman01la** [comment]
fixed in 783b8d2
