### ISSUE TITLE
Multiple predicate attributes doesn't work

### ISSUE THREAD

**Issue by kurtharriger** [roman01la/cljss#39]
I have the following with 3 different colors for complete active and pending / default.  But if either active? or complete? is true it renders the active color. If I reverse the order of the predicates it will then render the complete color if either is true.

```clojure
(defstyled Stepper-Step :li
  {:display :inline-block
   :padding "2em"
   :background step-color
   :complete? {:background complete-color}
   :active? {:background active-color}
   })
  ```

**Comment by roman01la** [comment]
I’ll look into this, thanks for reporting
