### ISSUE TITLE
inject-global requires 

### ISSUE THREAD

**Issue by lwhorton** [roman01la/cljss#42]
https://github.com/roman01la/cljss/blob/895152db118d81547b404598c457f11fcdd01738/src/cljss/core.clj#L172-L173

The way the `inject-global` macro is written it is currently impossible to refer to a symbol from another namespace. Unless I'm mistaken, the macro should probably attempt to resolve a given symbol at compile time via `(ns-resolve ...` or `(resolve ...`. The use case for this is defining some css elsewhere, say in `global-css-rules.core`, and then trying to `(inject-global global-css-rules.core/eric-meyer-reset-global)`.

**Comment by roman01la** [comment]
It's not possible since styles are processed in Clojure at compile time. AFAIK there's no way to resolve vars between ClojureScript and Clojure environments.

**Comment by lwhorton** [comment]
Okay, I understand. I should be able to get away with a `base_styles.clj` file that defines styles instead.

**Comment by roman01la** [comment]
I figured the macro could try to resolve a var and get its value. Just pushed `1.6.2`. `inject-global` and `font-face` now understand styles declarations referenced from *.clj namespaces.

**Comment by lwhorton** [comment]
Could this also be used in the root defstyled macro? Is there anything preventing a rule definition (in cljs) from referencing a clj variable? For the same above reasons, suppose I want to define a bunch of breakpoints. It would be really annoying to have to use `"768px"` in each and every `::css/media` query, where what I really want is something like `:max-width vars/medium-size-screens`. Is this possible with the current impl?

**Comment by lwhorton** [comment]
Nevermind - I think a satisfactory solution is to write my own macro and use it to `get-var` at compile time.
```
(var-get (ns-resolve 'css.vars (symbol sym)))
```

**Comment by lwhorton** [comment]
Could you speak a little more to this:
> It's not possible since styles are processed in Clojure at compile time. AFAIK there's no way to resolve vars between ClojureScript and Clojure environments.

I was attempting to write a macro that would compile-time swap out vars declared in a clj file. Mainly so I could just use some macro like `(get-var some-var-in-a-file)`:
```
(defstyled comp :section
  {:align-items "center"
   ::css/media {[[:max-width (get-var medium)]]
                {:align-items "flex-start"
                 }}})

(defmacro defstyled [sym element styles]
  (let [expanded (clojure.walk/macroexpand-all styles)]
    `(do
       (cljss.reagent/defstyled ~sym ~element ~expanded))
    )
  )
```
Except I'm bumping into an issue where `(get-var medium)` isn't actually expanded.
