### ISSUE TITLE
cleaning up of duplicates?

### ISSUE THREAD

**Issue by lwhorton** [roman01la/cljss#43]
Great job on this library. It's *almost* exactly what I was looking for on a new project, except for two issues. 

One: a side effect of using `defstyles` is that every time I invoke the fn generated by the macro, I get a new style chunk added to the `<style>` tag. If you style a component that's re-rendered frequently this can very quickly lead to an enormous style block inside your html head. Could we easily modify the behavior to essentially memoize the fn responsible for modifying the `<style>` tag? In my opinion we shouldn't be adding a so many new duplicate blocks of css into the DOM. Eventually this will lead to some detrimental effects, I fear.

<img width="491" alt="screen shot 2018-03-23 at 7 39 21 pm" src="https://user-images.githubusercontent.com/2663599/37859512-f30f9438-2ed1-11e8-8dae-c01857d806a0.png">

Two: it seems like the reagent integration is a bit ... too assuming? I haven't dug into the internals of how you're using `createClass`, but I get react dom validation errors such as `Warning: Unknown prop on-click on <a> tag. Remove this prop from the element`. If I use only a raw `[:a {:on-click #(...)}]` reagent has no issue hiding this "improper use" from react. It's almost like you're subverting part of the reagent pipeline?

**Comment by lwhorton** [comment]
To elaborate a little further, what I'd ultimately like to see beyond memoization is somple deduplication. If I render a 5-element list using reagent:

```
(into [:ol] (for [i [1 2 3 4 5]]
  [:li {:class (my-style-fn)} i])
```
I shouldn't see 5 instances of the exact same "my_module__my-style-fn-<hash>" appear in the root style tag, ya know?

**Comment by roman01la** [comment]
Styles duplication is definitely a bug. Regarding Reagent case I guess this happens when you use `defstyled`? If so, there's no runtime compilation from kebab case to camel case attributes. You have to pass camel based attributes into `defstyled` components.

**Comment by roman01la** [comment]
Runtime attrs conversion for `defstyled` landed in master

**Comment by roman01la** [comment]
styles duplication fix is landed in master as well
