### ISSUE TITLE
No explicit dependency on cljsjs.react

### ISSUE THREAD

**Issue by lwhorton** [roman01la/cljss#45]
There’s a hard dependency on `js/React` inside of the `reagent.clj` file — but you don't declare a dep in your project.clj on `cljsjs.react` or some sort of npm dep via `package.json` on `react`. I’m trying to ensure the load order of my own app guarantees `js/React` to exist before using `defstyled`, but I’m not sure its working. Mostly because I don’t know where to stick a require in there because of how `(make-styled)` works with the cljs/clj namespace (at-compile time defining a cljs var?). I *think* you could solve this by simply depending on `cljsjs.react` in the reagent cljs file?

**Comment by mattly** [comment]
The problem would still persist if you're otherwise bringing your own react or pulling it in via npm-deps. You can workaround the problem with this but i'd prefer to not have to
```
  (:require
   [cljss.reagent :as css.rg]
   [goog.object :as obj]
   [react :as react])

(obj/set js/window "React" react)
```

**Comment by kwladyka** [comment]
IMO dependency on `cljs.react` will be mistake. A lot of people use npm packages to get the newest version. I am one of them :) I can always use `:exclude`, but I think assumption there is `React` in dependency is right assumption.

BTW From my experience if you want use js dependencies like npm use `shadow-cljs`. All other solutions will fail.

**Comment by lwhorton** [comment]
After some thought, I think I'm okay with a wont-fix here. It does seem strange to rely on `cljsjs.react` in the macro itself, instead of it being provided elsewhere. I wonder if it might be better to _force_ people to do a `(set! js/window "React" impl)` and have the macro just pull from the window. In the end it doesn't seem like a huge issue, just a small gotchya.

**Comment by lwhorton** [comment]
Nevermind. After some thought, a dependency on `js/React` is way better than any alternative. Leave it up to consumers to "inject" their react implementation via `set! js/window "React" impl`.
