### ISSUE TITLE
:advanced optimizations has empty styles tag

### ISSUE THREAD

**Issue by alex-dixon** [roman01la/cljss#46]
Hey, thanks for the awesome library.

I'm not seeing any styled content after compiling with :advanced optimizations and setting `goog.DEBUG` to false. DOM nodes  reference classnames generated by the framework, but there aren't any definitions for them as far as I can tell. In development everything's working great and I see the class definitions injected into a style tag at the top of the page. In production the <style> node is still there but it's empty.

Any idea what I'm doing wrong?

Update: Set :optimizations to :whitespace and it works fine.

Update2: Looks like :whitespace worked because after setting optimizations to :whitespace goog.DEBUG evaluated to `true` despite no other changes in configuration....?

Update3: :whitespace doesn't support :closure-defines https://github.com/clojure/clojurescript-site/blob/master/content/reference/compiler-options.adoc#closure-defines

Ran again with optimzations :simple and goog.DEBUG is set to `false`, still no styles.

**Comment by roman01la** [comment]
Hey. Are you using the latest version? Could you please try an older one and let me know if it works? Thanks

**Comment by alex-dixon** [comment]
@roman01la I'm on 1.6.0. Should I try older than that?

**Comment by roman01la** [comment]
Wait, so you mean you don’t see styles in style tag but content is still styled on the page? If so, that’s fine. When compiling with debug turned off, the fast pass in enabled for generated CSS. These styles injected at runtime are not visible in style tag, but they are still there.

**Comment by roman01la** [comment]
@alex-dixon does this answer your question?

**Comment by alex-dixon** [comment]
Thanks. No the page has no styling. Good to know the empty style tag isn’t the cause. I tried rolling back to the last published version but ran into other issues. Browser is chrome. Can provide more info if it’s not reproducible.

**Comment by lwhorton** [comment]
I too have this issue. The fast-insert in `goog.DEBUG = false` does seem to add rules if you inspect the `<style>` tag's internal properties, but for some reason those rules don't take effect.

**Comment by lwhorton** [comment]
Some more debugging information:

It looks like the `vars-*` classes exist in the css ruleset, but not any properties defined in an autogen class. It _seems_ that styles defined with `::cljss/media` properties don't inject the ruleset into the dom.

<img width="800" alt="screen shot 2018-05-17 at 9 40 20 am" src="https://user-images.githubusercontent.com/2663599/40191474-84acee4a-59b6-11e8-807d-1e8c19e76fde.png">

What I would expect to see here is `main_views__menu-navigation-link-s` in the chrome inspector with a bunch of styles:
```
(defstyled menu-navigation-links-s :div
  {:display "grid"
   :grid-column-gap "2rem"
   :grid-template-columns "repeat(3, 1fr)"
   :justify-self "end"
   ::cljss/media {[[:max-width "900px"]]
                  {:grid-template-columns "1fr"
                   :position "fixed"
                   :right (with-meta #(if % "0" "-400px") :open?)
                   :top "0"
                   :transition "all .25s"
                   :bottom "0"
                   :display "flex"
                   :flex-direction "column"
                   :background "white"
                   :z-index "99"
                   :width "320px"}}})
```

Conversely, if you look at a defstyled without any ::cljss/media properties, everything works fine.

<img width="803" alt="screen shot 2018-05-17 at 9 45 18 am" src="https://user-images.githubusercontent.com/2663599/40191671-09fe9968-59b7-11e8-8ff8-dbebfe8c86ee.png">

```
(defstyled menu-navigation-s :nav
  {:display "grid"
   :grid-template-columns "1fr 2fr"
   :padding "1rem 0"
   :grid-column "content"})
```

I also tested the case where we provide a dynamic value from `with-meta`:

```
(defstyled menu-navigation-s :nav
  {:display "grid"
   :grid-template-columns "1fr 2fr"
   :padding "1rem 0"
   :background-color (with-meta identity :test)
   :grid-column "content"})
```
 It seems to properly inject the vars/generated class rulesets.

<img width="1052" alt="screen shot 2018-05-17 at 10 08 33 am" src="https://user-images.githubusercontent.com/2663599/40192860-69414bac-59ba-11e8-8dae-ce866eb26bc4.png">

**Comment by vvvvalvalval** [comment]
> @alex-dixon I think I've fixed it, please try with your code or example in the repo

> Closing for now. Let me know if this works or not for you

@roman01la I don't know if you ever got feedback from @alex-dixon , but I'm on `"1.6.4"` and getting similar symptoms:

1. in production build only, my CSS media queries defined via CLJSS don't seem to apply, while other styling properties work. 
2. setting goog.DEBUG to true makes the symptoms disappear.

Should I file a new issue?
