### ISSUE TITLE
Use symbol to reference styles in defstyled macro

### ISSUE THREAD

**Issue by bertofer** [roman01la/cljss#47]
First of all, thanks for the work on this library! I just discovered the whole css-in-js ecosystem and I am trying to apply it in clojurescript.

My use case: I want to use some style rules in different elements. I thought, maybe I can define the styles map as a variable, and then use it / merge it when defining the styled element, thus reusing some of the rules in different components.

Some simple code that exemplifies this: 
```clojure
(def click-icon-styles
  {:opacity 0.5
   :&:hover {:opacity 1
             :cursor "pointer"}})

(defstyled styled-clickable-icon :i
  click-icon-styles)
```
Figwheel on browser gives me the following error:
```clojure
(defstyled styled-clickable-icon :i
    ^--- Don't know how to create ISeq from: clojure.lang.Symbol
```

I am not sure if this is an issue or just not an intended use for the library. Is there any way to workaround for my use case? To merge different styles so I have less definition of styles to cover a larger set of components? I could try to open a PR or discuss a way to work on this if needs solving, although I am very new to the Clojure/Script langauge and community, would be of great practice.

Thanks!

**Comment by roman01la** [comment]
Hello 👋

Unfortunately this is not possible, because cljss is purely compile-time library when it comes to styles definition. It requires styles maps to be defined in place, so macro can compile it into static CSS that is injected at runtime, including dynamic parts. Allowing referencing vars and merging styles would mean to perform compilation at runtime which is itself is not very performant process, especially given ClojureScript's overhead.

**Comment by bertofer** [comment]
Hi @roman01la , thanks for the answer. In that case, would there be anyway to compose different styles? I think it's something that could be done in compile time too.

Right now the way I can think of is creating different `defstyles` and calling them in runtime to get the proper classnames and append them to the :class of the object.

Is that the proper way to go? 

Thanks!

**Comment by bertofer** [comment]
Developed a couple of functions that are very useful for this scenario:
```clojure
(defn with-styles [& styles]
  (str " " (s/join " " (for [s styles] (s)))))

(defn styled-component [tag styles]
  (fn [attrs & content]
    [tag (merge-with str attrs {:class (apply with-styles styles)})
     (for [c content] c)]))

;; And then creating components like
(def expand-icon (ui/styled-component :i [expand-icon-styles ui/clickable-icon-styles]))
```

This is a reasonable solution for me, this can be closed if you consider so @roman01la ;)

**Comment by roman01la** [comment]
You are right, the only way to compose styles is by combining class names. Some libraries in JS world provide a special syntax for this e.g.
```js
{
  composes: [cls1, cls2],
  color: "#000"
}
```

but in the end it's still string concatenation, so I prefer to leave this to developers.
