### ISSUE TITLE
Components composability

### ISSUE THREAD

**Issue by esseswann** [roman01la/cljss#48]
![image](https://user-images.githubusercontent.com/6066417/41033527-967a8d24-698f-11e8-905d-3fd03d2e7c86.png)

So `glamorous` allows composition of a kind `styledComponent + styledComponent + commonComponent + ...`. Is anything alike planned\possible at all?

**Comment by roman01la** [comment]
`defstyles` macro expands into a function that returns a class name when called, so composition is just a concatenation of multiple class names.
```clojure
(defstyles link []
  ...)

(defstyles hoverable []
  ...)

(defn container []
  (clojure.string/join " " [(link) (hoverable)])
```

`defstyled` macro expands into React component, compose them as usual components

**Comment by esseswann** [comment]
This is not the same, because you cannot use those components separately, like
```
(defn ReagentComponent []
 [[Link]
  [Hoverable]
  [Container]])
