### ISSUE TITLE
Trouble importing cljss.reagent 

### ISSUE THREAD

**Issue by vnctaing** [roman01la/cljss#56]
Hello I'm new to Clojurescript, 

I have generated my app with `lein new reagent`. I have some issue trying to import `cljs.reagent/defstyled`. I've installed it through lein, by adding it to `:dependencies` 

But when I'm trying to use it here in https://github.com/vnctaing/loo/commit/6a09c752943c7499adc8638e1bce080f97f7b237 with 

```
:require [cljss.reagent :refer [defstyled]]
```

I get : 

`Invalid :refer, var cljss.reagent/defstyled does not exist `

My minimal repo is available here: https://github.com/vnctaing/loo 

Is this correct the way of importing/using the library ?

**Comment by roman01la** [comment]
I think because defstyled is a macro you should go with :require-macros instead of :require

**Comment by roman01la** [comment]
Or you can go with :refer-macros instead

**Comment by vnctaing** [comment]
Thanks, I've been able to import the macro but when I call an example from the doc I get this error:

```
(defstyled h1 :h1
    ^--- Call to cljss.reagent/defstyled did not conform to spec.
```

I've also updated my minimal repo.

**Comment by vnctaing** [comment]
(It was just the example from the doc that weren't complying with the specs). Thanks for the help @roman01la
