### ISSUE TITLE
curious about plans for library

### ISSUE THREAD

**Issue by tomconnors** [roman01la/cljss#6]
Hi, I noticed you recently removed the defstyles macro and am curious what your plans are for this library. I like the css in cljs approach and would like to use it in a reagent project, but I prefer the defstyles macro to defstyled because the former seems more reusable and the latter requires the user to treat elements with styles specially.

**Comment by roman01la** [comment]
Hi! Thanks for letting me know! I removed it because I didn't need it, but that's fine I'll put it back shortly. Sorry for that 😅

**Comment by tomconnors** [comment]
I see you already put it back in, thanks a lot!

**Comment by roman01la** [comment]
FYI I've also added support for `defstyled` in different React wrappers like Rum, Om and Reagent.

**Comment by tomconnors** [comment]
Thanks for letting me know. I'm not sure what the advantage of defstyled is though, mind clarifying? Here's an example that makes defstyles look better to me:

``` clojure
(defstyles red-text
  {:color "red"})

(defn component-using-defstyles []
  [:div
   [:a {:class red-text}
    [:span "foo"]]])


(defstyled red-anchor :a
  {:color "red"})

(defn component-using-defstyled []
  [:div
   [red-anchor
    [:span "foo"]]])
```

The `red-text` class is reusable for different tags, but that isn't very important to me. What I care about is it seems better to not have to create another component for a tag just because it has styles. Am I missing something?

**Comment by roman01la** [comment]
Yes, sure. You can think of `defstyled` as a styling primitive that is on a higher level of abstraction than what `defstyles` provides. There's not much to it. If you prefer `defstyles` you definitely should use it, it's just that I prefer to operate on components level :)

**Comment by tomconnors** [comment]
Thanks for explaining. I'm about to open another unrelated issue. Sorry for the barrage.
