### ISSUE TITLE
Styles extraction

### ISSUE THREAD

**Issue by esseswann** [roman01la/cljss#8]
@roman01la Do you see any possibilities to implement styles extraction to a minified file like [emotion](https://github.com/tkh44/emotion/blob/master/docs/extract-mode.md) does?

**Comment by roman01la** [comment]
‪It was there in the previous version, implemented in a macro, but I removed this functionality because macros, state and side-effects doesn't play well together.

Also static extraction makes it impossible to leverage dead code elimination on styles.

**Comment by roman01la** [comment]
Static styles extraction means writing all styles into a file at compile time. Thus even unused styles will be dumped into that css file.

Without static extraction (all styles are shipped within JS bundle) unused styles are automatically removed by Closure compiler as usual unused code.
